# Materi Review Numpy

#### Import Module

In [2]:
import numpy as np
import math

#### Buatlah sebuah array yang berisikan angka 0 sebanyak 36 (1 dimensi)

In [2]:
np.zeros(36)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0.])

#### Buatlah sebuah array yang berisikan angka 0 sebanyak 36 (2 dimensi) - Dengan dimensi tidak harus n * n

In [7]:
np.zeros(36).reshape(12,3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### Buatlah sebuah array 1 dimensi yang berisikan angka 1.5

In [20]:
arr = np.ones(10) * 1.5
arr

array([1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5])

#### Buatlah sebuah array 1 dimensi yang berisikan nilai phi sebanyak 10

In [12]:
np.ones(10) * math.pi

array([3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
       3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265])

#### Buatlah sebuah array 1 dimensi dari 10 hingga 50 secara berurutan

In [21]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Buatlah sebuah array 1 dimensi dari 10 hingga 50 yang menampilkan hanya bilangan genap saja

In [22]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Buatlah sebuah array 2 dimensi dari 100 hingga 1 yang menampilkan hanya bilangan ganjil saja

In [26]:
np.arange(99,0,-2).reshape(10,5)

array([[99, 97, 95, 93, 91],
       [89, 87, 85, 83, 81],
       [79, 77, 75, 73, 71],
       [69, 67, 65, 63, 61],
       [59, 57, 55, 53, 51],
       [49, 47, 45, 43, 41],
       [39, 37, 35, 33, 31],
       [29, 27, 25, 23, 21],
       [19, 17, 15, 13, 11],
       [ 9,  7,  5,  3,  1]])

#### Buatlah maritix identitas dengan dimensi 10x10

In [27]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

#### Tampilkan 1 angka random antara 0 hingga 1

In [28]:
np.random.rand(1)

array([0.55350671])

#### Tampilkan 25 nilai dari distribusi normal standar kemudian kalikan hasilnya dengan angka terakhir tahun kelahiran mas/mba

In [31]:
np.random.randn(25)*7

array([-6.21065334, -1.59347852,  8.81484358,  1.31930988, -9.45687148,
       -0.08446069, -9.17257828, -9.76872266,  3.58206748,  5.37313656,
        1.40501714, 11.04227421, -6.55432467, -3.07122304, 15.75503135,
       -5.59430341,  6.9975057 , -7.72976807,  1.79769012,  6.50407818,
        0.98706772, -8.61692505, -1.48888191, 10.31298605, -8.37048674])

#### Buatlah matrix seperti dibawah ini

In [35]:
np.linspace(0.01,1.0,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Buatlah array dari 0 ke 1 yang terbagi rata sebanyak 30 

In [36]:
np.linspace(0,1,30)

array([0.        , 0.03448276, 0.06896552, 0.10344828, 0.13793103,
       0.17241379, 0.20689655, 0.24137931, 0.27586207, 0.31034483,
       0.34482759, 0.37931034, 0.4137931 , 0.44827586, 0.48275862,
       0.51724138, 0.55172414, 0.5862069 , 0.62068966, 0.65517241,
       0.68965517, 0.72413793, 0.75862069, 0.79310345, 0.82758621,
       0.86206897, 0.89655172, 0.93103448, 0.96551724, 1.        ])

## Numpy Indexing and Selection

#### Buatlah sebuah matrix seperti dibawah.

In [41]:
arr = np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### Dari matrix tersebut, tampilkan nilai dibawah ini

In [42]:
arr[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

#### Dari matrix tersebut, tampilkan nilai dibawah ini

In [43]:
arr[3,4]

20

#### Dari matrix tersebut, tampilkan nilai dibawah ini

In [46]:
arr[:3,1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

#### Dari matrix tersebut, tampilkan nilai dibawah ini

In [47]:
arr[4]

array([21, 22, 23, 24, 25])

#### Dari matrix tersebut, tampilkan nilai dibawah ini

In [48]:
arr[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Tentukan jumlahan dari komponen dalam matrix tersebut

In [49]:
arr.sum()

325

#### Tentukan Standar Deviasi dari komponen dalam matrix tersebut

In [50]:
arr.std()

7.211102550927978

#### Tentukan jumlahan dari Tiap tiap baris dalam matrix tersebut

In [53]:
arr.sum(axis=1)

array([ 15,  40,  65,  90, 115])